import { spawnSync } from "node:child_process";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { parseComponent, type ComponentSource } from "./parse-component.ts";

export { parseComponent } from "./parse-component.ts";

const marker = "-- Generated by elm-web-components. Do not edit.";

type Field = ComponentSource["inputs"][number];

export type BuildOptions = { app?: string; output?: string; componentFiles: string[]; optimize?: boolean };

type ElmApplication = {
  type: string;
  "source-directories": string[];
  "elm-version": string;
  dependencies: object;
  "test-dependencies": object;
};

const fail = (path: string, message: string): never => {
  throw new Error(`${path}: ${message}`);
};

const kebab = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replaceAll("_", "-").toLowerCase();

const attribute = (name: string) => kebab(name);

function decoder(field: Field): string {
  const key = JSON.stringify(field.attribute);

  if (field.type === "Maybe String") return `Decode.maybe (Decode.field ${key} Decode.string)`;

  if (field.type === "Bool") return `Decode.oneOf [ Decode.field ${key} Decode.string |> Decode.map (always True), Decode.succeed False ]`;

  return `Decode.field ${key} Decode.string`;
}

function encoder(field: Field): string {
  return `Encode.${field.type.toLowerCase()} detail.${field.name}`;
}

export function generatedElm(component: ComponentSource): string {
  const { module, suffix, inputs, outputs } = component;

  const record = `{ ${inputs.map((f) => `${f.name} = ${f.name}`).join(", ")} }`;

  const decode = inputs.length === 1
    ? `Decode.map (\\${inputs[0].name} -> ${record})\n        (${decoder(inputs[0])})`
    : `Decode.map${inputs.length} (\\${inputs.map((f) => f.name).join(" ")} -> ${record})\n${inputs.map((f) => `        (${decoder(f)})`).join("\n")}`;

  const cases = outputs.map((output) => `        ${module}.${output.name} detail ->\n            { name = ${JSON.stringify(output.event)}\n            , detail = Encode.object\n                [ ${output.fields.map((f) => `( ${JSON.stringify(attribute(f.name))}, ${encoder(f)} )`).join("\n                , ")}\n                ]\n            }`).join("\n\n");

  return `port module ElmWebComponents.Generated.${suffix} exposing (main)\n\nimport Component\nimport ${module}\nimport Json.Decode as Decode\nimport Json.Encode as Encode\nimport Platform.Cmd exposing (Cmd)\nimport Platform.Sub exposing (Sub)\n\nport inputChanged${suffix} : (Decode.Value -> msg) -> Sub msg\nport connectionChanged${suffix} : (Bool -> msg) -> Sub msg\nport outputSent${suffix} : Encode.Value -> Cmd msg\n\ndecodeInput : Decode.Decoder ${module}.Input\ndecodeInput =\n    ${decode}\n\nencodeOutput : ${module}.Output -> Component.Event\nencodeOutput output =\n    case output of\n${cases}\n\nmain =\n    Component.program decodeInput encodeOutput\n        { inputChanged = inputChanged${suffix}\n        , connectionChanged = connectionChanged${suffix}\n        , outputSent = outputSent${suffix}\n        }\n        ${module}.component\n`;
}

function hostAttribute(field: Field): string {
  const key = JSON.stringify(field.attribute);

  if (field.type === "String") return `[ Attr.attribute ${key} props.${field.name} ]`;

  if (field.type === "Bool") return `if props.${field.name} then [ Attr.attribute ${key} "" ] else []`;

  return `case props.${field.name} of\n                Just value -> [ Attr.attribute ${key} value ]\n                Nothing -> []`;
}

export function generatedHost(component: ComponentSource): string {
  const { module, tag, inputs, outputs } = component;

  const props = [
    ...inputs.map((field) => `${field.name} : ${field.type}`),
    ...outputs.map((output) => `on${output.name} : Maybe (${output.fields.length === 1 ? `{ ${output.fields[0].name} : ${output.fields[0].type} }` : `{ ${output.fields.map((f) => `${f.name} : ${f.type}`).join(", ")} }`} -> msg)`),
  ];

  const propsType = `{ ${props.join("\n    , ")}\n    }`;
  const attrs = inputs.map((field) => `        , ${hostAttribute(field)}`).join("\n");

  const listeners = outputs.map((output) => {
    const decoded = output.fields.length === 1
      ? `Decode.map (\\${output.fields[0].name} -> { ${output.fields[0].name} = ${output.fields[0].name} })\n                        (Decode.at [ "detail", ${JSON.stringify(attribute(output.fields[0].name))} ] Decode.${output.fields[0].type.toLowerCase()})`
      : `Decode.map${output.fields.length} (\\${output.fields.map((f) => f.name).join(" ")} -> { ${output.fields.map((f) => `${f.name} = ${f.name}`).join(", ")} })\n${output.fields.map((f) => `                        (Decode.at [ "detail", ${JSON.stringify(attribute(f.name))} ] Decode.${f.type.toLowerCase()})`).join("\n")}`;

    return `        , case props.on${output.name} of\n            Just toMsg ->\n                [ Events.on ${JSON.stringify(output.event)} (Decode.map toMsg (${decoded})) ]\n            Nothing ->\n                []`;
  }).join("\n");

  return `${marker}\nmodule WebComponents.${module} exposing (Props, view)\n\nimport Html exposing (Html)\nimport Html.Attributes as Attr\nimport Html.Events as Events\nimport Json.Decode as Decode\n\ntype alias Props msg =\n    ${propsType}\n\nview : Props msg -> List (Html msg) -> Html msg\nview props children =\n    Html.node ${JSON.stringify(tag)}\n        (List.concat\n            [ []\n${attrs}\n${listeners}\n            ]\n        )\n        children\n`;
}

export function generatedAdapter({ tag, suffix, inputs }: ComponentSource): string {
  const attributes = inputs.map((field) => field.attribute);

  return `\n(() => {\n  const program = Elm.ElmWebComponents.Generated.${suffix};\n  const observed = ${JSON.stringify(attributes)};\n  class ComponentElement extends HTMLElement {\n    static get observedAttributes() { return observed; }\n    connectedCallback() {\n      if (this.app) { this.app.ports.connectionChanged${suffix}.send(true); return; }\n      const root = this.attachShadow({ mode: "open" });\n      const mount = document.createElement("div");\n      root.append(mount);\n      this.app = program.init({ node: mount, flags: this.attributeSnapshot() });\n      this.app.ports.outputSent${suffix}.subscribe((events) => {\n        for (const { name, detail } of events) {\n          this.dispatchEvent(new CustomEvent(name, { detail, bubbles: true, composed: true }));\n        }\n      });\n    }\n    disconnectedCallback() {\n      if (this.app) this.app.ports.connectionChanged${suffix}.send(false);\n    }\n    attributeChangedCallback() {\n      if (this.app) this.app.ports.inputChanged${suffix}.send(this.attributeSnapshot());\n    }\n    attributeSnapshot() {\n      const snapshot = {};\n      for (const name of observed) {\n        if (this.hasAttribute(name)) snapshot[name] = this.getAttribute(name);\n      }\n      return snapshot;\n    }\n  }\n  customElements.define(${JSON.stringify(tag)}, ComponentElement);\n})();\n`;
}

function elmBinary(project: string): string {
  if (process.env.ELM_BINARY) return process.env.ELM_BINARY;
  let directory = project;

  while (true) {
    const local = resolve(directory, "node_modules/.bin/elm");

    if (existsSync(local)) return local;
    const parent = dirname(directory);

    if (parent === directory) return "elm";
    directory = parent;
  }
}

function removeGeneratedHosts(directory: string): void {
  if (!existsSync(directory)) return;

  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);

    if (entry.isDirectory()) removeGeneratedHosts(path);
    else if (entry.name.endsWith(".elm") && readFileSync(path, "utf8").startsWith(marker)) unlinkSync(path);
  }
}

function withBuildLock<T>(project: string, action: () => T): T {
  const directory = resolve(project, ".elm-web-components");
  mkdirSync(directory, { recursive: true });
  const lock = resolve(directory, "build.lock");
  let descriptor: number;

  try {
    descriptor = openSync(lock, "wx");
    writeFileSync(descriptor, String(process.pid));
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "EEXIST") fail(lock, "another build is running; remove this lock only if that build has stopped");
    throw error;
  }

  try {
    return action();
  } finally {
    closeSync(descriptor);
    unlinkSync(lock);
  }
}

export async function build({ app, output = "dist/components.js", componentFiles, optimize = false }: BuildOptions, project = process.cwd()): Promise<void> {
  const elmJson: ElmApplication = JSON.parse(readFileSync(resolve(project, "elm.json"), "utf8"));

  if (elmJson.type !== "application" || !Array.isArray(elmJson["source-directories"])) fail("elm.json", "expected an Elm application with source-directories");

  if (!componentFiles?.length) fail("build", "pass at least one component Elm file");

  if (!output.endsWith(".js")) fail("build", "--output must end in .js");
  const sources = elmJson["source-directories"].map((dir) => resolve(project, dir));

  const components = await Promise.all(componentFiles.map(async (file) => {
    const path = resolve(project, file);

    const sourceRoot = sources.find((source) => path.startsWith(source + sep));

    if (!sourceRoot) return fail(file, "component must be inside an Elm source directory");
    const component = await parseComponent(path);
    const expected = resolve(sourceRoot, ...component.module.split(".")) + ".elm";

    if (path !== expected) fail(file, `module ${component.module} must be at ${expected}`);

    return component;
  }));

  const tags = new Set();

  for (const component of components) {
    if (tags.has(component.tag)) fail(component.path, `duplicate tag ${component.tag}`);
    tags.add(component.tag);
    const path = resolve(sources[0], "WebComponents", ...component.module.split(".")) + ".elm";

    if (existsSync(path) && !readFileSync(path, "utf8").startsWith(marker)) fail(path, "generated host module would overwrite a handwritten file");
  }

  return withBuildLock(project, () => {
    removeGeneratedHosts(resolve(sources[0], "WebComponents"));

    for (const component of components) {
      const path = resolve(sources[0], "WebComponents", ...component.module.split(".")) + ".elm";
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generatedHost(component));
    }

    const buildDirectory = resolve(project, ".elm-web-components", "bundle");

    const entries = components.map((component) => {
      const name = `src/ElmWebComponents/Generated/${component.suffix}.elm`;
      const path = resolve(buildDirectory, name);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generatedElm(component));

      return name;
    });

    writeFileSync(resolve(buildDirectory, "elm.json"), JSON.stringify({
      ...elmJson,
      "source-directories": ["src", ...sources.map((source) => relative(buildDirectory, source))],
    }, null, 4) + "\n");
    const compiled = resolve(buildDirectory, "compiled.js");
    const args = ["make", ...entries, ...(app ? [resolve(project, app)] : []), `--output=${compiled}`, ...(optimize ? ["--optimize"] : [])];
    const result = spawnSync(elmBinary(project), args, { cwd: buildDirectory, env: process.env, stdio: "inherit" });

    if (result.error) throw result.error;

    if (result.status !== 0) throw new Error("Elm build failed.");
    const destination = resolve(project, output);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, readFileSync(compiled, "utf8") + components.map(generatedAdapter).join(""));
    process.stdout.write(`Built ${relative(project, destination)}: ${components.map((c) => `<${c.tag}>`).join(", ")}${app ? ` and ${app}` : ""}\n`);
  });
}
