import { spawnSync } from "node:child_process";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";

const marker = "-- Generated by elm-web-components. Do not edit.";

const wireTypes = new Set(["String", "Bool", "Int", "Float"]);

type Field = { name: string; type: string; attribute: string };

type Output = { name: string; fields: Field[]; event: string };

export type ComponentSource = {
  path: string;
  module: string;
  tag: string;
  suffix: string;
  inputs: Field[];
  outputs: Output[];
};

export type BuildOptions = { app?: string; output?: string; componentFiles: string[]; optimize?: boolean };

type ElmApplication = {
  type: string;
  "source-directories": string[];
  "elm-version": string;
  dependencies: object;
  "test-dependencies": object;
};

const fail = (path: string, message: string, source?: string, offset = 0): never => {
  const line = source === undefined ? "" : `:${source.slice(0, offset).split("\n").length}`;
  throw new Error(`${path}${line}: ${message}`);
};

const kebab = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replaceAll("_", "-").toLowerCase();

const attribute = (name: string) => kebab(name);

export function generatedName(tag: string) {
  return `Tag${Buffer.from(tag, "utf8").toString("hex")}`;
}

function fields(body: string, path: string, allowed: ReadonlySet<string>, source: string, offset: number): Field[] {
  const parts = body.trim().split(/\s*,\s*/).filter(Boolean);

  if (!parts.length) fail(path, "a record needs at least one field");

  return parts.map((part) => {
    const match = /^([a-z][A-Za-z0-9_]*)\s*:\s*(Maybe\s+String|String|Bool|Int|Float)$/.exec(part.trim());

    const type = match?.[2]?.replace(/\s+/g, " ");

    if (!match || !type || !allowed.has(type)) return fail(path, `unsupported field ${JSON.stringify(part.trim())}; supported types: ${[...allowed].join(", ")}`, source, offset);

    return { name: match[1], type, attribute: attribute(match[1]) };
  });
}

function exposingList(source: string, start: number, path: string): string {
  let depth = 0;

  for (let index = start; index < source.length; index++) {
    if (source[index] === "(") depth++;

    if (source[index] === ")") depth--;

    if (depth === 0) return source.slice(start + 1, index);
  }

  return fail(path, "module exposing list is not closed", source, start);
}

export function parseComponent(path: string): ComponentSource {
  const source = readFileSync(path, "utf8");
  const moduleMatch = /^module\s+([A-Z][\w]*(?:\.[A-Z][\w]*)+)\s+exposing\s*\(/m.exec(source);

  if (!moduleMatch) return fail(path, "expected a namespaced module declaration, such as Ui.DatePicker");
  const module = moduleMatch[1];
  const exposed = exposingList(source, moduleMatch.index + moduleMatch[0].lastIndexOf("("), path);

  if (!/\bcomponent\b/.test(exposed) || !/\bOutput\s*\(\.\.\)/.test(exposed)) {
    fail(path, "expose component and Output(..) so the generated entry can use them");
  }

  if (!new RegExp(`^component\\s*:\\s*Component(?:\\.Component)?\\s+Input\\s+\\w+\\s+\\w+\\s+Output\\s*$`, "m").test(source)) {
    fail(path, "expected component : Component Input State Msg Output (with your State and Msg names)");
  }

  if (!/component\s*=\s*Component\.define\b/.test(source)) fail(path, "expected component = Component.define");
  const inputMatch = /^type alias Input\s*=\s*\{([^}]+)\}/m.exec(source);

  if (!inputMatch) return fail(path, "expected type alias Input = { ... }");
  const inputs = fields(inputMatch[1], path, new Set(["String", "Maybe String", "Bool"]), source, inputMatch.index);
  const outputMatch = /^type Output\s*=\s*/m.exec(source);

  if (!outputMatch) return fail(path, "expected type Output = EventName { field : String }");

  const outputBody = source.slice(outputMatch.index + outputMatch[0].length);
  const outputs: Output[] = [];
  let cursor = 0;

  while (true) {
    const match = /^\s*([A-Z][A-Za-z0-9]*)\s+\{([^}]+)\}/.exec(outputBody.slice(cursor));

    if (!match) return fail(path, "expected Output constructor with a flat record payload", source, outputMatch.index + outputMatch[0].length + cursor);

    const outputFields = fields(match[2], path, wireTypes, source, outputMatch.index + outputMatch[0].length + cursor);

    if (outputFields.length > 8) fail(path, "at most eight Output fields are supported in v1", source, outputMatch.index + outputMatch[0].length + cursor);

    if (new Set(outputFields.map((field) => field.attribute)).size !== outputFields.length) fail(path, "Output fields map to duplicate event detail keys", source, outputMatch.index + outputMatch[0].length + cursor);

    outputs.push({ name: match[1], fields: outputFields, event: kebab(match[1]) });
    cursor += match[0].length;
    const separator = /^\s*\|/.exec(outputBody.slice(cursor));

    if (!separator) break;

    cursor += separator[0].length;
  }

  if (inputs.length > 8) fail(path, "at most eight Input fields are supported in v1", source, inputMatch.index);

  if (new Set(inputs.map((field) => field.attribute)).size !== inputs.length) fail(path, "Input fields map to duplicate attribute names", source, inputMatch.index);

  if (new Set(outputs.map((output) => output.event)).size !== outputs.length) fail(path, "Output constructors map to duplicate event names", source, outputMatch.index);

  const tag = module.split(".").map(kebab).join("-");
  const suffix = generatedName(tag);

  return { path, module, tag, suffix, inputs, outputs };
}

function decoder(field: Field): string {
  const key = JSON.stringify(field.attribute);

  if (field.type === "Maybe String") return `Decode.maybe (Decode.field ${key} Decode.string)`;

  if (field.type === "Bool") return `Decode.oneOf [ Decode.field ${key} Decode.string |> Decode.map (always True), Decode.succeed False ]`;

  return `Decode.field ${key} Decode.string`;
}

function encoder(field: Field): string {
  return `Encode.${field.type.toLowerCase()} detail.${field.name}`;
}

export function generatedElm(component: ComponentSource): string {
  const { module, suffix, inputs, outputs } = component;

  const record = `{ ${inputs.map((f) => `${f.name} = ${f.name}`).join(", ")} }`;

  const decode = inputs.length === 1
    ? `Decode.map (\\${inputs[0].name} -> ${record})\n        (${decoder(inputs[0])})`
    : `Decode.map${inputs.length} (\\${inputs.map((f) => f.name).join(" ")} -> ${record})\n${inputs.map((f) => `        (${decoder(f)})`).join("\n")}`;

  const cases = outputs.map((output) => `        ${module}.${output.name} detail ->\n            { name = ${JSON.stringify(output.event)}\n            , detail = Encode.object\n                [ ${output.fields.map((f) => `( ${JSON.stringify(attribute(f.name))}, ${encoder(f)} )`).join("\n                , ")}\n                ]\n            }`).join("\n\n");

  return `port module ElmWebComponents.Generated.${suffix} exposing (main)\n\nimport Component\nimport ${module}\nimport Json.Decode as Decode\nimport Json.Encode as Encode\nimport Platform.Cmd exposing (Cmd)\nimport Platform.Sub exposing (Sub)\n\nport inputChanged${suffix} : (Decode.Value -> msg) -> Sub msg\nport connectionChanged${suffix} : (Bool -> msg) -> Sub msg\nport outputSent${suffix} : Encode.Value -> Cmd msg\n\ndecodeInput : Decode.Decoder ${module}.Input\ndecodeInput =\n    ${decode}\n\nencodeOutput : ${module}.Output -> Component.Event\nencodeOutput output =\n    case output of\n${cases}\n\nmain =\n    Component.program decodeInput encodeOutput\n        { inputChanged = inputChanged${suffix}\n        , connectionChanged = connectionChanged${suffix}\n        , outputSent = outputSent${suffix}\n        }\n        ${module}.component\n`;
}

function hostAttribute(field: Field): string {
  const key = JSON.stringify(field.attribute);

  if (field.type === "String") return `[ Attr.attribute ${key} props.${field.name} ]`;

  if (field.type === "Bool") return `if props.${field.name} then [ Attr.attribute ${key} "" ] else []`;

  return `case props.${field.name} of\n                Just value -> [ Attr.attribute ${key} value ]\n                Nothing -> []`;
}

export function generatedHost(component: ComponentSource): string {
  const { module, tag, inputs, outputs } = component;

  const props = [
    ...inputs.map((field) => `${field.name} : ${field.type}`),
    ...outputs.map((output) => `on${output.name} : Maybe (${output.fields.length === 1 ? `{ ${output.fields[0].name} : ${output.fields[0].type} }` : `{ ${output.fields.map((f) => `${f.name} : ${f.type}`).join(", ")} }`} -> msg)`),
  ];

  const propsType = `{ ${props.join("\n    , ")}\n    }`;
  const attrs = inputs.map((field) => `        , ${hostAttribute(field)}`).join("\n");

  const listeners = outputs.map((output) => {
    const decoded = output.fields.length === 1
      ? `Decode.map (\\${output.fields[0].name} -> { ${output.fields[0].name} = ${output.fields[0].name} })\n                        (Decode.at [ "detail", ${JSON.stringify(attribute(output.fields[0].name))} ] Decode.${output.fields[0].type.toLowerCase()})`
      : `Decode.map${output.fields.length} (\\${output.fields.map((f) => f.name).join(" ")} -> { ${output.fields.map((f) => `${f.name} = ${f.name}`).join(", ")} })\n${output.fields.map((f) => `                        (Decode.at [ "detail", ${JSON.stringify(attribute(f.name))} ] Decode.${f.type.toLowerCase()})`).join("\n")}`;

    return `        , case props.on${output.name} of\n            Just toMsg ->\n                [ Events.on ${JSON.stringify(output.event)} (Decode.map toMsg (${decoded})) ]\n            Nothing ->\n                []`;
  }).join("\n");

  return `${marker}\nmodule WebComponents.${module} exposing (Props, view)\n\nimport Html exposing (Html)\nimport Html.Attributes as Attr\nimport Html.Events as Events\nimport Json.Decode as Decode\n\ntype alias Props msg =\n    ${propsType}\n\nview : Props msg -> List (Html msg) -> Html msg\nview props children =\n    Html.node ${JSON.stringify(tag)}\n        (List.concat\n            [ []\n${attrs}\n${listeners}\n            ]\n        )\n        children\n`;
}

export function generatedAdapter({ tag, suffix, inputs }: ComponentSource): string {
  const attributes = inputs.map((field) => field.attribute);

  return `\n(() => {\n  const program = Elm.ElmWebComponents.Generated.${suffix};\n  const observed = ${JSON.stringify(attributes)};\n  class ComponentElement extends HTMLElement {\n    static get observedAttributes() { return observed; }\n    connectedCallback() {\n      if (this.app) { this.app.ports.connectionChanged${suffix}.send(true); return; }\n      const root = this.attachShadow({ mode: "open" });\n      const mount = document.createElement("div");\n      root.append(mount);\n      this.app = program.init({ node: mount, flags: this.attributeSnapshot() });\n      this.app.ports.outputSent${suffix}.subscribe((events) => {\n        for (const { name, detail } of events) {\n          this.dispatchEvent(new CustomEvent(name, { detail, bubbles: true, composed: true }));\n        }\n      });\n    }\n    disconnectedCallback() {\n      if (this.app) this.app.ports.connectionChanged${suffix}.send(false);\n    }\n    attributeChangedCallback() {\n      if (this.app) this.app.ports.inputChanged${suffix}.send(this.attributeSnapshot());\n    }\n    attributeSnapshot() {\n      const snapshot = {};\n      for (const name of observed) {\n        if (this.hasAttribute(name)) snapshot[name] = this.getAttribute(name);\n      }\n      return snapshot;\n    }\n  }\n  customElements.define(${JSON.stringify(tag)}, ComponentElement);\n})();\n`;
}

function elmBinary(project: string): string {
  if (process.env.ELM_BINARY) return process.env.ELM_BINARY;
  let directory = project;

  while (true) {
    const local = resolve(directory, "node_modules/.bin/elm");

    if (existsSync(local)) return local;
    const parent = dirname(directory);

    if (parent === directory) return "elm";
    directory = parent;
  }
}

function removeGeneratedHosts(directory: string): void {
  if (!existsSync(directory)) return;

  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);

    if (entry.isDirectory()) removeGeneratedHosts(path);
    else if (entry.name.endsWith(".elm") && readFileSync(path, "utf8").startsWith(marker)) unlinkSync(path);
  }
}

function withBuildLock<T>(project: string, action: () => T): T {
  const directory = resolve(project, ".elm-web-components");
  mkdirSync(directory, { recursive: true });
  const lock = resolve(directory, "build.lock");
  let descriptor: number;

  try {
    descriptor = openSync(lock, "wx");
    writeFileSync(descriptor, String(process.pid));
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "EEXIST") fail(lock, "another build is running; remove this lock only if that build has stopped");
    throw error;
  }

  try {
    return action();
  } finally {
    closeSync(descriptor);
    unlinkSync(lock);
  }
}

export function build({ app, output = "dist/components.js", componentFiles, optimize = false }: BuildOptions, project = process.cwd()): void {
  const elmJson: ElmApplication = JSON.parse(readFileSync(resolve(project, "elm.json"), "utf8"));

  if (elmJson.type !== "application" || !Array.isArray(elmJson["source-directories"])) fail("elm.json", "expected an Elm application with source-directories");

  if (!componentFiles?.length) fail("build", "pass at least one component Elm file");

  if (!output.endsWith(".js")) fail("build", "--output must end in .js");
  const sources = elmJson["source-directories"].map((dir) => resolve(project, dir));

  const components = componentFiles.map((file) => {
    const path = resolve(project, file);

    const sourceRoot = sources.find((source) => path.startsWith(source + sep));

    if (!sourceRoot) return fail(file, "component must be inside an Elm source directory");
    const component = parseComponent(path);
    const expected = resolve(sourceRoot, ...component.module.split(".")) + ".elm";

    if (path !== expected) fail(file, `module ${component.module} must be at ${expected}`);

    return component;
  });

  const tags = new Set();

  for (const component of components) {
    if (tags.has(component.tag)) fail(component.path, `duplicate tag ${component.tag}`);
    tags.add(component.tag);
    const path = resolve(sources[0], "WebComponents", ...component.module.split(".")) + ".elm";

    if (existsSync(path) && !readFileSync(path, "utf8").startsWith(marker)) fail(path, "generated host module would overwrite a handwritten file");
  }

  return withBuildLock(project, () => {
    removeGeneratedHosts(resolve(sources[0], "WebComponents"));

    for (const component of components) {
      const path = resolve(sources[0], "WebComponents", ...component.module.split(".")) + ".elm";
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generatedHost(component));
    }

    const buildDirectory = resolve(project, ".elm-web-components", "bundle");

    const entries = components.map((component) => {
      const name = `src/ElmWebComponents/Generated/${component.suffix}.elm`;
      const path = resolve(buildDirectory, name);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generatedElm(component));

      return name;
    });

    writeFileSync(resolve(buildDirectory, "elm.json"), JSON.stringify({
      ...elmJson,
      "source-directories": ["src", ...sources.map((source) => relative(buildDirectory, source))],
    }, null, 4) + "\n");
    const compiled = resolve(buildDirectory, "compiled.js");
    const args = ["make", ...entries, ...(app ? [resolve(project, app)] : []), `--output=${compiled}`, ...(optimize ? ["--optimize"] : [])];
    const result = spawnSync(elmBinary(project), args, { cwd: buildDirectory, env: process.env, stdio: "inherit" });

    if (result.error) throw result.error;

    if (result.status !== 0) throw new Error("Elm build failed.");
    const destination = resolve(project, output);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, readFileSync(compiled, "utf8") + components.map(generatedAdapter).join(""));
    process.stdout.write(`Built ${relative(project, destination)}: ${components.map((c) => `<${c.tag}>`).join(", ")}${app ? ` and ${app}` : ""}\n`);
  });
}
