import { spawnSync } from "node:child_process";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { homedir } from "node:os";
import { parseComponent, type ComponentSource } from "./parse-component.ts";

export { parseComponent } from "./parse-component.ts";

const marker = "-- Generated by elm-web-components. Do not edit.";

export type BuildOptions = { app?: string; output?: string; componentFiles: string[]; optimize?: boolean };

type ElmApplication = {
  type: string;
  "source-directories": string[];
  "elm-version": string;
  dependencies: { direct: Record<string, string>; indirect: Record<string, string> };
  "test-dependencies": object;
};

const fail = (path: string, message: string): never => {
  throw new Error(`${path}: ${message}`);
};

export function generatedElm(component: ComponentSource): string {
  return component.elm;
}

export function generatedHost(component: ComponentSource): string {
  return component.host;
}

export function generatedAdapter(component: ComponentSource): string {
  return component.adapter;
}

function elmBinary(project: string): string {
  if (process.env.ELM_BINARY) return process.env.ELM_BINARY;
  let directory = project;

  while (true) {
    const local = resolve(directory, "node_modules/.bin/elm");

    if (existsSync(local)) return local;
    const parent = dirname(directory);

    if (parent === directory) return "elm";
    directory = parent;
  }
}

function removeGeneratedHosts(directory: string): void {
  if (!existsSync(directory)) return;

  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);

    if (entry.isDirectory()) removeGeneratedHosts(path);
    else if (entry.name.endsWith(".elm") && readFileSync(path, "utf8").startsWith(marker)) unlinkSync(path);
  }
}


function projectModules(directory: string): Array<{ path: string; contents: string }> {
  if (!existsSync(directory)) return [];

  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name === "WebComponents") return [];
    const path = resolve(directory, entry.name);

    if (entry.isDirectory()) return projectModules(path);

    if (!entry.name.endsWith(".elm")) return [];

    return [{ path, contents: readFileSync(path, "utf8") }];
  });
}

function packageDocs(elmJson: ElmApplication): Array<{ name: string; docs: string }> {
  const home = process.env.ELM_HOME ?? resolve(homedir(), ".elm");
  const dependencies = { ...elmJson.dependencies.direct, ...elmJson.dependencies.indirect };

  return Object.entries(dependencies).flatMap(([name, version]) => {
    const path = resolve(home, elmJson["elm-version"], "packages", name, version, "docs.json");

    return existsSync(path) ? [{ name, docs: readFileSync(path, "utf8") }] : [];
  });
}

function withBuildLock<T>(project: string, action: () => T): T {
  const directory = resolve(project, ".elm-web-components");
  mkdirSync(directory, { recursive: true });
  const lock = resolve(directory, "build.lock");
  let descriptor: number;

  try {
    descriptor = openSync(lock, "wx");
    writeFileSync(descriptor, String(process.pid));
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "EEXIST") fail(lock, "another build is running; remove this lock only if that build has stopped");
    throw error;
  }

  try {
    return action();
  } finally {
    closeSync(descriptor);
    unlinkSync(lock);
  }
}

export async function build({ app, output = "dist/components.js", componentFiles, optimize = false }: BuildOptions, project = process.cwd()): Promise<void> {
  const elmJson: ElmApplication = JSON.parse(readFileSync(resolve(project, "elm.json"), "utf8"));

  if (elmJson.type !== "application" || !Array.isArray(elmJson["source-directories"])) fail("elm.json", "expected an Elm application with source-directories");

  if (!componentFiles?.length) fail("build", "pass at least one component Elm file");

  if (!output.endsWith(".js")) fail("build", "--output must end in .js");
  const sources = elmJson["source-directories"].map((dir) => resolve(project, dir));
  const modules = sources.flatMap(projectModules);
  const packages = packageDocs(elmJson);

  const components = await Promise.all(componentFiles.map(async (file) => {
    const path = resolve(project, file);

    const sourceRoot = sources.find((source) => path.startsWith(source + sep));

    if (!sourceRoot) return fail(file, "component must be inside an Elm source directory");
    const component = await parseComponent(path, modules, packages);
    const expected = resolve(sourceRoot, ...component.module.split(".")) + ".elm";

    if (path !== expected) fail(file, `module ${component.module} must be at ${expected}`);

    return component;
  }));

  const tags = new Set();

  for (const component of components) {
    if (tags.has(component.tag)) fail(component.path, `duplicate tag ${component.tag}`);
    tags.add(component.tag);
    const path = resolve(sources[0], "WebComponents", ...component.module.split(".")) + ".elm";

    if (existsSync(path) && !readFileSync(path, "utf8").startsWith(marker)) fail(path, "generated host module would overwrite a handwritten file");
    const codecPath = resolve(sources[0], "WebComponents", "Codecs", component.suffix + ".elm");

    if (existsSync(codecPath) && !readFileSync(codecPath, "utf8").startsWith(marker)) fail(codecPath, "generated codec module would overwrite a handwritten file");
  }

  return withBuildLock(project, () => {
    removeGeneratedHosts(resolve(sources[0], "WebComponents"));

    for (const component of components) {
      const path = resolve(sources[0], "WebComponents", ...component.module.split(".")) + ".elm";
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generatedHost(component));

      const codecPath = resolve(sources[0], "WebComponents", "Codecs", component.suffix + ".elm");
      mkdirSync(dirname(codecPath), { recursive: true });
      writeFileSync(codecPath, component.codec);
    }

    const buildDirectory = resolve(project, ".elm-web-components", "bundle");

    const entries = components.map((component) => {
      const name = `src/ElmWebComponents/Generated/${component.suffix}.elm`;
      const path = resolve(buildDirectory, name);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generatedElm(component));

      return name;
    });

    writeFileSync(resolve(buildDirectory, "elm.json"), JSON.stringify({
      ...elmJson,
      "source-directories": ["src", ...sources.map((source) => relative(buildDirectory, source))],
    }, null, 4) + "\n");
    const compiled = resolve(buildDirectory, "compiled.js");
    const args = ["make", ...entries, ...(app ? [resolve(project, app)] : []), `--output=${compiled}`, ...(optimize ? ["--optimize"] : [])];
    const result = spawnSync(elmBinary(project), args, { cwd: buildDirectory, env: process.env, stdio: "inherit" });

    if (result.error) throw result.error;

    if (result.status !== 0) throw new Error("Elm build failed.");
    const destination = resolve(project, output);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, readFileSync(compiled, "utf8") + components.map(generatedAdapter).join(""));
    process.stdout.write(`Built ${relative(project, destination)}: ${components.map((c) => `<${c.tag}>`).join(", ")}${app ? ` and ${app}` : ""}\n`);
  });
}
